name: Setup and test

on: [ push, pull_request ]

jobs:
  tests:
    name: Composer setup and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]
        laravel: [ 10.*, 9.* ]
        include:
          - laravel: 10.*
            testbench: 8.*
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest
      - name: Run tests
        run: |
          composer validate --strict
